services:
  initia:
    environment:
      - SEEDS=${SEEDS}
      - PEERS=${PEERS}
      - GENESIS_URL=${GENESIS_URL}
      - ADDRBOOK_URL=${ADDRBOOK_URL}
      - CHAIN_ID=${CHAIN_ID}
      - MONIKER=${MONIKER}
      - ORACLE_URL=${ORACLE_URL}
      - RECOVER_FROM_SNAPSHOTS=${RECOVER_FROM_SNAPSHOTS}
    image: kantandadui/initia:latest
    container_name: initia
    pull_policy: always
    depends_on:
      - initia-slinky
    networks:
      - initia-network
    ports:
      - '26657'
      - '26656'
    command: ['/bin/sh', '-c', '/app/init.sh && initiad start']
    volumes:
      - initia_data:/root/.initia
      - ${SNAPSHOTS_PATH}:/root/metadata

  initia-slinky:
    image: kantandadui/initia-slinky:latest
    container_name: initia-slinky
    pull_policy: always
    networks:
      - initia-network
    command:
      [
        './slinky',
        '--oracle-config-path',
        './oracle.json',
        '--market-map-endpoint',
        '${MARKET_MAP_ENDPOINT}',
      ]

networks:
  initia-network:
    driver: bridge

volumes:
  initia_data:
